[0m2021.07.20 16:55:16 INFO  Started: Metals version 0.10.5 in workspace 'C:\Users\Shahrez\Documents\Revature\P0' for client Visual Studio Code 1.57.1.[0m
[0m2021.07.20 16:55:17 INFO  time: initialize in 1.02s[0m
[0m2021.07.20 16:55:19 WARN  Build server is not auto-connectable.[0m
[0m2021.07.20 16:55:19 WARN  no build tool detected in workspace 'C:\Users\Shahrez\Documents\Revature\P0'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. [0m
[0m2021.07.20 16:55:19 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala[0m
[0m2021.07.20 16:55:23 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.20 16:55:26 INFO  time: code lens generation in 7.35s[0m
[0m2021.07.20 16:56:44 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\build.sbt[0m
Jul 20, 2021 4:58:39 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 77
Jul 20, 2021 4:58:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 80
Jul 20, 2021 4:58:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 86
[0m2021.07.20 16:58:43 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala[0m
[0m2021.07.20 16:58:46 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\build.sbt[0m
[0m2021.07.20 16:59:09 INFO  running 'C:\Program Files\Java\jdk1.8.0_161\bin\java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Dsbt.version=1.5.4 -jar C:\Users\Shahrez\AppData\Local\Temp\metals2956239807604733507\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
[0m2021.07.20 16:59:10 ERROR [info] [launcher] getting org.scala-sbt sbt 1.5.4  (this may take some time)...[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.14/scala-library-2.12.14.jar ...[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.5.4/sbt-1.5.4.jar ...[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.5.1/io_2.12-1.5.1.jar ...[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.5.4/main_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:21 ERROR :: loading settings :: url = jar:file:/C:/Users/Shahrez/AppData/Local/Temp/metals2956239807604733507/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml[0m
[0m2021.07.20 16:59:21 ERROR :: loading settings :: url = jar:file:/C:/Users/Shahrez/AppData/Local/Temp/metals2956239807604733507/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml[0m
[0m2021.07.20 16:59:21 ERROR :: loading settings :: url = jar:file:/C:/Users/Shahrez/AppData/Local/Temp/metals2956239807604733507/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml[0m
[0m2021.07.20 16:59:21 ERROR :: loading settings :: url = jar:file:/C:/Users/Shahrez/AppData/Local/Temp/metals2956239807604733507/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml[0m
[0m2021.07.20 16:59:21 ERROR 	[SUCCESSFUL ] org.scala-sbt#sbt;1.5.4!sbt.jar (428ms)[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.5.4/logic_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:21 ERROR 	[SUCCESSFUL ] org.scala-sbt#io_2.12;1.5.1!io_2.12.jar (558ms)[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.5.4/actions_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:21 ERROR 	[SUCCESSFUL ] org.scala-sbt#logic_2.12;1.5.4!logic_2.12.jar (230ms)[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.5.4/main-settings_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:21 ERROR 	[SUCCESSFUL ] org.scala-sbt#actions_2.12;1.5.4!actions_2.12.jar (228ms)[0m
[0m2021.07.20 16:59:21 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.5.4/run_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#run_2.12;1.5.4!run_2.12.jar (235ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.5.4/command_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#main-settings_2.12;1.5.4!main-settings_2.12.jar (551ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.5.4/collections_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#command_2.12;1.5.4!command_2.12.jar (210ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/scripted-plugin_2.12/1.5.4/scripted-plugin_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#scripted-plugin_2.12;1.5.4!scripted-plugin_2.12.jar (87ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-lm-integration_2.12/1.5.4/zinc-lm-integration_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.14!scala-library.jar (1346ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.5.4/util-logging_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#collections_2.12;1.5.4!collections_2.12.jar (133ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.3.2/launcher-interface-1.3.2.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-lm-integration_2.12;1.5.4!zinc-lm-integration_2.12.jar (92ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.5.2/librarymanagement-core_2.12-1.5.2.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.3.2!launcher-interface.jar (97ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.5.2/librarymanagement-ivy_2.12-1.5.2.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-logging_2.12;1.5.4!util-logging_2.12.jar (142ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.5.5/compiler-interface-1.5.5.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#compiler-interface;1.5.5!compiler-interface.jar (156ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.5.5/zinc-compile_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#librarymanagement-ivy_2.12;1.5.2!librarymanagement-ivy_2.12.jar (223ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.5.4/util-relation_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-relation_2.12;1.5.4!util-relation_2.12.jar (79ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.5.4/util-position_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#librarymanagement-core_2.12;1.5.2!librarymanagement-core_2.12.jar (321ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.14/scala-reflect-2.12.14.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-compile_2.12;1.5.5!zinc-compile_2.12.jar (113ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.5.4/completion_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-position_2.12;1.5.4!util-position_2.12.jar (93ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.5.4/task-system_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#completion_2.12;1.5.4!completion_2.12.jar (140ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.5.4/tasks_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#task-system_2.12;1.5.4!task-system_2.12.jar (104ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.5.4/testing_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#main_2.12;1.5.4!main_2.12.jar (1996ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.5.4/util-tracking_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:22 ERROR 	[SUCCESSFUL ] org.scala-sbt#tasks_2.12;1.5.4!tasks_2.12.jar (97ms)[0m
[0m2021.07.20 16:59:22 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.5.5/zinc-classpath_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-tracking_2.12;1.5.4!util-tracking_2.12.jar (89ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.5.5/zinc-apiinfo_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.12;1.5.5!zinc-classpath_2.12.jar (108ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.5.5/zinc_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#testing_2.12;1.5.4!testing_2.12.jar (164ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.5.4/util-control_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.12;1.5.5!zinc-apiinfo_2.12.jar (118ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.5.4/util-interface-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc_2.12;1.5.5!zinc_2.12.jar (108ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.5.4/core-macros_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-control_2.12;1.5.4!util-control_2.12.jar (141ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.14/scala-compiler-2.12.14.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-interface;1.5.4!util-interface.jar (108ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.5.4/util-cache_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#core-macros_2.12;1.5.4!core-macros_2.12.jar (103ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.5.4/test-agent-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#test-agent;1.5.4!test-agent.jar (103ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.5.5/compiler-bridge_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#util-cache_2.12;1.5.4!util-cache_2.12.jar (132ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.5.5/zinc-classfile_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.12;1.5.5!zinc-classfile_2.12.jar (104ms)[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#compiler-bridge_2.12;1.5.5!compiler-bridge_2.12.jar (131ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.5.5/zinc-persist_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.5.5/zinc-core_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-persist_2.12;1.5.5!zinc-persist_2.12.jar (157ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.5.5/zinc-compile-core_2.12-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-core_2.12;1.5.5!zinc-core_2.12.jar (189ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.5.5/zinc-persist-core-assembly-1.5.5.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.12;1.5.5!zinc-compile-core_2.12.jar (164ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.5.4/protocol_2.12-1.5.4.jar ...[0m
[0m2021.07.20 16:59:23 ERROR 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.14!scala-reflect.jar (1183ms)[0m
[0m2021.07.20 16:59:23 ERROR downloading https://repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.3.1/ipcsocket-1.3.1.jar ...[0m
[0m2021.07.20 16:59:24 ERROR 	[SUCCESSFUL ] org.scala-sbt.ipcsocket#ipcsocket;1.3.1!ipcsocket.jar (179ms)[0m
[0m2021.07.20 16:59:24 ERROR 	[SUCCESSFUL ] org.scala-sbt#protocol_2.12;1.5.4!protocol_2.12.jar (311ms)[0m
[0m2021.07.20 16:59:24 ERROR 	[SUCCESSFUL ] org.scala-sbt#zinc-persist-core-assembly;1.5.5!zinc-persist-core-assembly.jar (571ms)[0m
[0m2021.07.20 16:59:26 ERROR 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.14!scala-compiler.jar (2567ms)[0m
[0m2021.07.20 16:59:26 ERROR :: retrieving :: org.scala-sbt#boot-app[0m
[0m2021.07.20 16:59:26 ERROR 	confs: [default][0m
[0m2021.07.20 16:59:26 ERROR 	83 artifacts copied, 0 already retrieved[0m
[0m2021.07.20 16:59:26 ERROR [info] [launcher] getting Scala 2.12.14 (for sbt)...[0m
[0m2021.07.20 16:59:26 ERROR :: retrieving :: org.scala-sbt#boot-scala[0m
[0m2021.07.20 16:59:26 ERROR 	confs: [default][0m
[0m2021.07.20 16:59:26 ERROR 	6 artifacts copied, 0 already retrieved[0m
[0m2021.07.20 16:59:31 INFO  [info] Updated file C:\Users\Shahrez\Documents\Revature\P0\project\build.properties: set sbt.version to 1.5.4[0m
[0m2021.07.20 16:59:31 INFO  [info] welcome to sbt 1.5.4 (Oracle Corporation Java 1.8.0_161)[0m
[0m2021.07.20 16:59:39 INFO  [info] loading settings for project p0-build-build from metals.sbt ...[0m
[0m2021.07.20 16:59:41 INFO  [info] loading project definition from C:\Users\Shahrez\Documents\Revature\P0\project\project[0m
[0m2021.07.20 16:59:49 INFO  [info] loading settings for project p0-build from metals.sbt ...[0m
[0m2021.07.20 16:59:49 INFO  [info] loading project definition from C:\Users\Shahrez\Documents\Revature\P0\project[0m
Jul 20, 2021 4:59:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 98
[0m2021.07.20 17:00:03 INFO  [success] Generated .bloop\p0-build.json[0m
[0m2021.07.20 17:00:03 INFO  [success] Total time: 14 s, completed Jul 20, 2021 5:00:04 PM[0m
[0m2021.07.20 17:00:06 INFO  [info] loading settings for project p0 from build.sbt ...[0m
[0m2021.07.20 17:00:06 INFO  [info] set current project to test (in build file:/C:/Users/Shahrez/Documents/Revature/P0/)[0m
[0m2021.07.20 17:00:08 INFO  [success] Generated .bloop\p0-test.json[0m
[0m2021.07.20 17:00:08 INFO  [success] Generated .bloop\p0.json[0m
[0m2021.07.20 17:00:08 INFO  [success] Total time: 1 s, completed Jul 20, 2021 5:00:08 PM[0m
[0m2021.07.20 17:00:08 INFO  sbt bloopInstall exit: 0[0m
[0m2021.07.20 17:00:08 INFO  time: ran 'sbt bloopInstall' in 59s[0m
[0m2021.07.20 17:00:08 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 18233'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading 2 projects from 'c:\Users\Shahrez\Documents\Revature\P0\.bloop'...
[0m[32m[D][0m Loading project from 'c:\Users\Shahrez\Documents\Revature\P0\.bloop\p0-test.json'
[0m[32m[D][0m Loading project from 'c:\Users\Shahrez\Documents\Revature\P0\.bloop\p0.json'
[0m[32m[D][0m Cache miss for scala instance org.scala-lang:scala-compiler:2.12.14.
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\jansi.jar
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\jline.jar
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\scala-compiler.jar
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\scala-library.jar
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\scala-reflect.jar
[0m[32m[D][0m   => C:\Users\Shahrez\.sbt\boot\scala-2.12.14\lib\scala-xml_2.12.jar
[0m[32m[D][0m Missing analysis file for project 'p0'
[0m[32m[D][0m Missing analysis file for project 'p0-test'
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:18233...
The server is listening for incoming connections at tcp://127.0.0.1:18233...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 17:00:09 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 17:00:11 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 40851'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:40851...
The server is listening for incoming connections at tcp://127.0.0.1:40851...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 17:00:11 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 17:00:11 INFO  time: Connected to build server in 3.02s[0m
[0m2021.07.20 17:00:11 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.20 17:00:12 INFO  time: Imported build in 0.15s[0m
[0m2021.07.20 17:00:18 INFO  time: indexed workspace in 6.76s[0m
[0m2021.07.20 17:05:39 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 17:06:12 INFO  time: compiled p0 in 32s[0m
[0m2021.07.20 18:24:55 INFO  shutting down Metals[0m
[0m2021.07.20 18:24:55 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 18:24:55 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 19:12:02 INFO  Started: Metals version 0.10.5 in workspace 'C:\Users\Shahrez\Documents\Revature\P0' for client Visual Studio Code 1.57.1.[0m
[0m2021.07.20 19:12:03 INFO  time: initialize in 1.09s[0m
[0m2021.07.20 19:12:05 INFO  Attempting to connect to the build server...[0m
[0m2021.07.20 19:12:05 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala[0m
[0m2021.07.20 19:12:05 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\build.sbt[0m
[0m2021.07.20 19:12:06 INFO  skipping build import with status 'Installed'[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 43060'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:43060...
The server is listening for incoming connections at tcp://127.0.0.1:43060...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:12:08 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:12:08 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 17444'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:17444...
The server is listening for incoming connections at tcp://127.0.0.1:17444...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:12:09 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:12:09 INFO  time: Connected to build server in 4.59s[0m
[0m2021.07.20 19:12:09 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.20 19:12:11 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.20 19:12:11 INFO  time: Imported build in 0.15s[0m
[0m2021.07.20 19:12:12 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.20 19:12:17 INFO  time: code lens generation in 11s[0m
[0m2021.07.20 19:12:18 INFO  time: code lens generation in 12s[0m
Jul 20, 2021 7:12:18 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 10
Jul 20, 2021 7:12:18 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 11
[0m2021.07.20 19:12:18 INFO  time: code lens generation in 3.09s[0m
Jul 20, 2021 7:12:18 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 16
[0m2021.07.20 19:12:20 INFO  time: code lens generation in 2.28s[0m
[0m2021.07.20 19:12:22 INFO  time: indexed workspace in 10s[0m
Jul 20, 2021 7:14:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 62
Jul 20, 2021 7:14:09 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 68
[0m2021.07.20 19:15:13 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 19:15:14 ERROR text document: file:///c:/Users/Shahrez/Documents/Revature/P0/src/main/scala/main.scala
java.nio.file.NoSuchFileException: c:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.Semanticdbs$.loadResolvedTextDocument(Semanticdbs.scala:68)
	at scala.meta.internal.mtags.Semanticdbs$.loadTextDocument(Semanticdbs.scala:50)
	at scala.meta.internal.metals.FileSystemSemanticdbs.textDocument(FileSystemSemanticdbs.scala:48)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:30)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:36)
	at scala.meta.internal.metals.CodeLensProvider.findLenses(CodeLensProvider.scala:22)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$2(MetalsLanguageServer.scala:1507)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$1(MetalsLanguageServer.scala:1505)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m
[0m2021.07.20 19:15:15 INFO  time: compiled p0 in 1.29s[0m
[0m2021.07.20 19:15:17 ERROR text document: file:///c:/Users/Shahrez/Documents/Revature/P0/src/main/scala/main.scala
java.nio.file.NoSuchFileException: c:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.Semanticdbs$.loadResolvedTextDocument(Semanticdbs.scala:68)
	at scala.meta.internal.mtags.Semanticdbs$.loadTextDocument(Semanticdbs.scala:50)
	at scala.meta.internal.metals.FileSystemSemanticdbs.textDocument(FileSystemSemanticdbs.scala:48)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:30)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:36)
	at scala.meta.internal.metals.CodeLensProvider.findLenses(CodeLensProvider.scala:22)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$2(MetalsLanguageServer.scala:1507)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$1(MetalsLanguageServer.scala:1505)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m
[0m2021.07.20 19:15:17 INFO  shutting down Metals[0m
[0m2021.07.20 19:15:17 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 19:15:18 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 19:15:45 INFO  Started: Metals version 0.10.5 in workspace 'C:\Users\Shahrez\Documents\Revature\P0' for client Visual Studio Code 1.57.1.[0m
[0m2021.07.20 19:15:46 INFO  time: initialize in 1.39s[0m
[0m2021.07.20 19:15:48 INFO  Attempting to connect to the build server...[0m
Jul 20, 2021 7:15:48 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///c%3A/Users/Shahrez/Documents/Revature/P0/src/main/scala/main.scala",
      "languageId": "scala",
      "version": 1,
      "text": ""
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.nio.file.NoSuchFileException: c:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.metals.MetalsLanguageServer.didOpen(MetalsLanguageServer.scala:956)
	... 16 more

[0m2021.07.20 19:15:48 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\build.sbt[0m
[0m2021.07.20 19:15:48 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\QUADRAT.scala[0m
[0m2021.07.20 19:15:48 INFO  skipping build import with status 'Installed'[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 45345'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:45345...
The server is listening for incoming connections at tcp://127.0.0.1:45345...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:15:52 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:15:52 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 25806'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:25806...
The server is listening for incoming connections at tcp://127.0.0.1:25806...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:15:53 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:15:53 INFO  time: Connected to build server in 5.13s[0m
[0m2021.07.20 19:15:53 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.20 19:15:55 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
Jul 20, 2021 7:15:55 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 4
[0m2021.07.20 19:15:56 INFO  time: Imported build in 0.31s[0m
[0m2021.07.20 19:15:57 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.20 19:16:02 ERROR text document: file:///c:/Users/Shahrez/Documents/Revature/P0/src/main/scala/main.scala
java.nio.file.NoSuchFileException: c:\Users\Shahrez\Documents\Revature\P0\src\main\scala\main.scala
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.metals.InteractiveSemanticdbs.$anonfun$textDocument$1(InteractiveSemanticdbs.scala:77)
	at java.util.HashMap.compute(HashMap.java:1197)
	at java.util.Collections$SynchronizedMap.compute(Collections.java:2682)
	at scala.meta.internal.metals.InteractiveSemanticdbs.textDocument(InteractiveSemanticdbs.scala:76)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:30)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:36)
	at scala.meta.internal.metals.CodeLensProvider.findLenses(CodeLensProvider.scala:22)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$2(MetalsLanguageServer.scala:1507)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$1(MetalsLanguageServer.scala:1505)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m
[0m2021.07.20 19:16:02 INFO  time: code lens generation in 14s[0m
Jul 20, 2021 7:16:05 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8
Jul 20, 2021 7:16:05 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 9
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 10
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 16
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 14
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 23
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 25
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 31
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 35
Jul 20, 2021 7:16:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 32
[0m2021.07.20 19:16:07 INFO  time: indexed workspace in 11s[0m
Jul 20, 2021 7:21:38 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 51
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 51)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 44)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 49)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 48)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 46)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[<error>]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 45)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[String]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 49)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[String]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 49)
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[String]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 36, 36, 49)
Jul 20, 2021 7:27:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 220
Jul 20, 2021 7:27:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 257
[0m2021.07.20 19:27:43 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 19:27:47 INFO  time: compiled p0 in 3.56s[0m
[0m2021.07.20 19:27:48 INFO  running 'C:\Program Files\Java\jdk1.8.0_161\bin\java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\Shahrez\AppData\Local\Temp\metals5330210733522732210\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
Jul 20, 2021 7:27:48 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
[0m2021.07.20 19:27:54 INFO  [info] welcome to sbt 1.5.4 (Oracle Corporation Java 1.8.0_161)[0m
[0m2021.07.20 19:27:58 INFO  [info] loading settings for project p0-build-build from metals.sbt ...[0m
[0m2021.07.20 19:28:00 INFO  [info] loading project definition from C:\Users\Shahrez\Documents\Revature\P0\project\project[0m
[0m2021.07.20 19:28:03 INFO  [info] loading settings for project p0-build from metals.sbt ...[0m
[0m2021.07.20 19:28:03 INFO  [info] loading project definition from C:\Users\Shahrez\Documents\Revature\P0\project[0m
[0m2021.07.20 19:28:10 INFO  [success] Generated .bloop\p0-build.json[0m
[0m2021.07.20 19:28:10 INFO  [success] Total time: 7 s, completed Jul 20, 2021 7:28:10 PM[0m
[0m2021.07.20 19:28:15 INFO  [info] loading settings for project p0 from build.sbt ...[0m
[0m2021.07.20 19:28:15 INFO  [info] set current project to QUADRAT (in build file:/C:/Users/Shahrez/Documents/Revature/P0/)[0m
[0m2021.07.20 19:28:17 INFO  [success] Generated .bloop\p0-test.json[0m
[0m2021.07.20 19:28:17 INFO  [success] Generated .bloop\p0.json[0m
[0m2021.07.20 19:28:17 INFO  [success] Total time: 1 s, completed Jul 20, 2021 7:28:17 PM[0m
[0m2021.07.20 19:28:17 INFO  sbt bloopInstall exit: 0[0m
[0m2021.07.20 19:28:17 INFO  time: ran 'sbt bloopInstall' in 28s[0m
[0m2021.07.20 19:28:17 INFO  Disconnecting from Bloop session...[0m
No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 19:28:17 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.20 19:28:17 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
[0m2021.07.20 19:28:17 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 40298'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:40298...
The server is listening for incoming connections at tcp://127.0.0.1:40298...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:28:17 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:28:17 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 19425'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:19425...
The server is listening for incoming connections at tcp://127.0.0.1:19425...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.20 19:28:18 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.20 19:28:18 INFO  time: Connected to build server in 1.21s[0m
[0m2021.07.20 19:28:18 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.20 19:28:20 INFO  time: indexed workspace in 2.04s[0m
Jul 20, 2021 7:29:33 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 304
Jul 20, 2021 7:29:39 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 310
Jul 20, 2021 7:30:19 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
Jul 20, 2021 7:30:23 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 328
Jul 20, 2021 7:30:24 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 334
Jul 20, 2021 7:30:53 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
Jul 20, 2021 7:31:07 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
Jul 20, 2021 7:31:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 362
Jul 20, 2021 7:32:07 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
[0m2021.07.20 19:32:22 INFO  Listening for transport dt_socket at address: 64268[0m
[0m2021.07.20 19:32:22 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 19:32:22 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 19:32:23 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 19:32:23 INFO  Trying to attach to remote debuggee VM 127.0.0.1:64268 .[0m
[0m2021.07.20 19:32:23 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 19:32:23 INFO  Hey yall[0m
[0m2021.07.20 19:32:23 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.20 19:39:20 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 19:39:20 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 11m 2.462s)[0m
[0m2021.07.20 19:39:20 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 19:39:21 INFO  time: compiled p0 in 1.17s[0m
[0m2021.07.20 19:39:26 INFO  Listening for transport dt_socket at address: 52734[0m
[0m2021.07.20 19:39:26 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 19:39:26 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 19:39:26 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 19:39:26 INFO  Trying to attach to remote debuggee VM 127.0.0.1:52734 .[0m
[0m2021.07.20 19:39:26 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 19:39:27 INFO  Welcome to QUADRAT, a program that allows you to effortlessly solve quadratic equations![0m
[0m2021.07.20 19:39:26 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 20, 2021 7:39:27 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: java.net.SocketException: Socket closed
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.net.SocketException: Socket closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at scala.meta.internal.metals.debug.SocketEndpoint.consume(SocketEndpoint.scala:22)
	at scala.meta.internal.metals.debug.MessageIdAdapter.consume(MessageIdAdapter.scala:43)
	at scala.meta.internal.metals.debug.ServerAdapter.send(ServerAdapter.scala:30)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleClientMessage$1(DebugProxy.scala:96)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:26)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToClient$1(DebugProxy.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 21 more

Jul 20, 2021 7:40:55 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
Jul 20, 2021 7:40:55 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.reflect.internal.Definitions$DefinitionsClass.isByNameParamType(Definitions.scala:417)
	at scala.reflect.internal.TreeInfo.isStableIdent(TreeInfo.scala:140)
	at scala.reflect.internal.TreeInfo.isStableIdentifier(TreeInfo.scala:113)
	at scala.reflect.internal.TreeInfo.isPath(TreeInfo.scala:102)
	at scala.reflect.internal.TreeInfo.admitsTypeSelection(TreeInfo.scala:158)
	at scala.tools.nsc.interactive.Global.stabilizedType(Global.scala:960)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:808)
	at scala.meta.internal.pc.SignatureHelpProvider.signatureHelp(SignatureHelpProvider.scala:23)

[0m2021.07.20 21:38:54 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:38:54 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 10m 36.158s)[0m
[0m2021.07.20 21:38:54 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:38:55 INFO  time: compiled p0 in 1.64s[0m
[0m2021.07.20 21:39:00 INFO  Listening for transport dt_socket at address: 62880[0m
[0m2021.07.20 21:39:01 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 21:39:01 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 21:39:01 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 21:39:01 INFO  Trying to attach to remote debuggee VM 127.0.0.1:62880 .[0m
[0m2021.07.20 21:39:01 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 21:39:01 INFO  Welcome to the Quadratic Formula Solver,[0m
[0m2021.07.20 21:39:01 INFO  a program that allows you to effortlessly[0m
[0m2021.07.20 21:39:01 INFO  solve quadratic equations![0m
[0m2021.07.20 21:39:01 INFO  [0m
[0m2021.07.20 21:39:01 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.20 21:49:25 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:49:25 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 21m 8.07s)[0m
[0m2021.07.20 21:49:25 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:49:27 INFO  time: compiled p0 in 1.16s[0m
[0m2021.07.20 21:49:31 INFO  Listening for transport dt_socket at address: 52363[0m
[0m2021.07.20 21:49:32 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 21:49:32 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 21:49:32 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 21:49:31 INFO  Trying to attach to remote debuggee VM 127.0.0.1:52363 .[0m
[0m2021.07.20 21:49:31 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 21:49:32 INFO  Welcome to the Quadratic Formula Solver,[0m
[0m2021.07.20 21:49:32 INFO  a program that allows you to effortlessly[0m
[0m2021.07.20 21:49:32 INFO  solve quadratic equations![0m
[0m2021.07.20 21:49:32 INFO  [0m
[0m2021.07.20 21:49:32 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.20 21:49:32 INFO  from the equation of the form ax^2 + bx + c = 0[0m
[0m2021.07.20 21:49:32 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.20 21:52:48 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:52:48 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 24m 30.474s)[0m
[0m2021.07.20 21:52:48 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:52:49 INFO  time: compiled p0 in 1.33s[0m
[0m2021.07.20 21:52:54 INFO  Listening for transport dt_socket at address: 57238[0m
[0m2021.07.20 21:52:54 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 21:52:54 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 21:52:54 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 21:52:54 INFO  Trying to attach to remote debuggee VM 127.0.0.1:57238 .[0m
[0m2021.07.20 21:52:54 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 21:52:55 INFO  Welcome to QUADRAT,[0m
[0m2021.07.20 21:52:55 INFO  a program that allows you to effortlessly[0m
[0m2021.07.20 21:52:55 INFO  solve quadratic equations![0m
[0m2021.07.20 21:52:55 INFO  [0m
[0m2021.07.20 21:52:55 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.20 21:52:55 INFO  from the equation of the form ax^2 + bx + c = 0[0m
[0m2021.07.20 21:52:55 ERROR ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2[0m
[0m2021.07.20 21:52:55 ERROR JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [util.c:840][0m
[0m2021.07.20 21:52:54 ERROR unexpected error during source scanning
java.lang.RuntimeException: invalid symbol format
#
^
	at scala.sys.package$.error(package.scala:30)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.fail(Scala.scala:200)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.readChar(Scala.scala:213)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseValue(Scala.scala:231)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseDescriptor(Scala.scala:256)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.entryPoint(Scala.scala:279)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser$.apply(Scala.scala:287)
	at scala.meta.internal.semanticdb.Scala$ScalaSymbolOps.owner(Scala.scala:101)
	at scala.meta.internal.mtags.Symbol.toplevel(Symbol.scala:56)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:149)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:129)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:116)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:116)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definitions(OnDemandSymbolIndex.scala:48)
	at scala.meta.internal.metals.DestinationProvider.definition(DefinitionProvider.scala:297)
	at scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:335)
	at scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:355)
	at scala.meta.internal.metals.DefinitionProvider.fromSymbol(DefinitionProvider.scala:104)
	at scala.meta.internal.metals.StacktraceAnalyzer.findLocationForSymbol$1(StacktraceAnalyzer.scala:71)
	at scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$2(StacktraceAnalyzer.scala:76)
	at scala.PartialFunction$Unlifted.applyOrElse(PartialFunction.scala:237)
	at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:180)
	at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:167)
	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
	at scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$1(StacktraceAnalyzer.scala:76)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.StacktraceAnalyzer.fileLocationFromLine(StacktraceAnalyzer.scala:74)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1(DebugProxy.scala:124)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1$adapted(DebugProxy.scala:99)
	at scala.meta.internal.metals.debug.ServerAdapter.$anonfun$onReceived$1(ServerAdapter.scala:25)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:26)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
	at scala.meta.internal.metals.debug.ServerAdapter.onReceived(ServerAdapter.scala:18)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToServer$1(DebugProxy.scala:65)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m
[0m2021.07.20 21:52:54 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.20 21:56:05 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:56:05 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 27m 48.091s)[0m
[0m2021.07.20 21:56:05 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 21:56:07 INFO  time: compiled p0 in 0.97s[0m
[0m2021.07.20 21:56:11 INFO  Listening for transport dt_socket at address: 49547[0m
[0m2021.07.20 21:56:11 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 21:56:11 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 21:56:11 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 21:56:11 INFO  Trying to attach to remote debuggee VM 127.0.0.1:49547 .[0m
[0m2021.07.20 21:56:11 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 21:56:12 INFO  Welcome to QUADRAT,[0m
[0m2021.07.20 21:56:12 INFO  a program that allows you to effortlessly[0m
[0m2021.07.20 21:56:12 INFO  solve quadratic equations![0m
[0m2021.07.20 21:56:12 INFO  [0m
[0m2021.07.20 21:56:12 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.20 21:56:12 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.20 21:56:11 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 20, 2021 10:02:19 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:24 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:25 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:25 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:25 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:25 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:25 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:29 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:31 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:31 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:32 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:02:32 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 20, 2021 10:03:12 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2058
[0m2021.07.20 22:07:02 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 22:07:02 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 38m 45.132s)[0m
[0m2021.07.20 22:07:02 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 22:07:04 INFO  time: compiled p0 in 1.28s[0m
[0m2021.07.20 22:07:08 INFO  Listening for transport dt_socket at address: 53144[0m
[0m2021.07.20 22:07:08 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 22:07:08 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 22:07:09 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 22:07:08 INFO  Trying to attach to remote debuggee VM 127.0.0.1:53144 .[0m
[0m2021.07.20 22:07:08 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 22:07:09 INFO  Welcome to QUADRAT,[0m
[0m2021.07.20 22:07:09 INFO  a program that allows you to effortlessly[0m
[0m2021.07.20 22:07:09 INFO  solve quadratic equations![0m
[0m2021.07.20 22:07:09 INFO  [0m
[0m2021.07.20 22:07:09 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.20 22:07:09 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.20 22:07:09 INFO  also, here's a test: ?[0m
[0m2021.07.20 22:07:09 ERROR ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2[0m
[0m2021.07.20 22:07:09 ERROR JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [util.c:840][0m
[0m2021.07.20 22:07:08 ERROR unexpected error during source scanning
java.lang.RuntimeException: invalid symbol format
#
^
	at scala.sys.package$.error(package.scala:30)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.fail(Scala.scala:200)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.readChar(Scala.scala:213)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseValue(Scala.scala:231)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.parseDescriptor(Scala.scala:256)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser.entryPoint(Scala.scala:279)
	at scala.meta.internal.semanticdb.Scala$DescriptorParser$.apply(Scala.scala:287)
	at scala.meta.internal.semanticdb.Scala$ScalaSymbolOps.owner(Scala.scala:101)
	at scala.meta.internal.mtags.Symbol.toplevel(Symbol.scala:56)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:149)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:129)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:116)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:116)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definitions(OnDemandSymbolIndex.scala:48)
	at scala.meta.internal.metals.DestinationProvider.definition(DefinitionProvider.scala:297)
	at scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:335)
	at scala.meta.internal.metals.DestinationProvider.fromSymbol(DefinitionProvider.scala:355)
	at scala.meta.internal.metals.DefinitionProvider.fromSymbol(DefinitionProvider.scala:104)
	at scala.meta.internal.metals.StacktraceAnalyzer.findLocationForSymbol$1(StacktraceAnalyzer.scala:71)
	at scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$2(StacktraceAnalyzer.scala:76)
	at scala.PartialFunction$Unlifted.applyOrElse(PartialFunction.scala:237)
	at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:180)
	at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:167)
	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
	at scala.meta.internal.metals.StacktraceAnalyzer.$anonfun$fileLocationFromLine$1(StacktraceAnalyzer.scala:76)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.StacktraceAnalyzer.fileLocationFromLine(StacktraceAnalyzer.scala:74)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1(DebugProxy.scala:124)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleServerMessage$1$adapted(DebugProxy.scala:99)
	at scala.meta.internal.metals.debug.ServerAdapter.$anonfun$onReceived$1(ServerAdapter.scala:25)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:26)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
	at scala.meta.internal.metals.debug.ServerAdapter.onReceived(ServerAdapter.scala:18)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToServer$1(DebugProxy.scala:65)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m
[0m2021.07.20 22:07:09 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.20 22:11:51 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 22:11:51 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2h 43m 34.038s)[0m
[0m2021.07.20 22:11:51 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.20 22:11:53 INFO  time: compiled p0 in 1.1s[0m
[0m2021.07.20 22:11:57 INFO  Listening for transport dt_socket at address: 63390[0m
[0m2021.07.20 22:11:57 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.20 22:11:57 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.20 22:11:57 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.20 22:11:57 INFO  Trying to attach to remote debuggee VM 127.0.0.1:63390 .[0m
[0m2021.07.20 22:11:57 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.20 22:11:58 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.20 22:11:58 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.20 22:11:58 INFO  [0m
[0m2021.07.20 22:11:58 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.20 22:11:58 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.20 22:11:58 INFO  also, here's a test: ?[0m
[0m2021.07.20 22:11:57 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 10:03:29 INFO  shutting down Metals[0m
[0m2021.07.21 10:03:29 INFO  Shut down connection with build server.[0m
[0m2021.07.21 10:03:29 INFO  Shut down connection with build server.[0m
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
[0m2021.07.21 17:37:23 INFO  Started: Metals version 0.10.5 in workspace 'C:\Users\Shahrez\Documents\Revature\P0' for client Visual Studio Code 1.57.1.[0m
[0m2021.07.21 17:37:27 INFO  time: initialize in 4.33s[0m
[0m2021.07.21 17:37:32 INFO  Attempting to connect to the build server...[0m
[0m2021.07.21 17:37:33 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\QUADRAT.scala[0m
[0m2021.07.21 17:37:34 INFO  skipping build import with status 'Installed'[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 41400'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:41400...
The server is listening for incoming connections at tcp://127.0.0.1:41400...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.21 17:37:46 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.21 17:37:46 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 29856'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:29856...
The server is listening for incoming connections at tcp://127.0.0.1:29856...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.21 17:37:50 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.21 17:37:50 INFO  time: Connected to build server in 17s[0m
[0m2021.07.21 17:37:50 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.21 17:37:53 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.21 17:37:54 INFO  time: Imported build in 1.14s[0m
[0m2021.07.21 17:37:58 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.21 17:38:05 INFO  time: code lens generation in 30s[0m
[0m2021.07.21 17:38:09 INFO  time: indexed workspace in 14s[0m
[0m2021.07.21 17:39:17 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:39:17 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 1m 31.144s)[0m
[0m2021.07.21 17:39:17 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:39:29 INFO  time: compiled p0 in 11s[0m
[0m2021.07.21 17:39:36 INFO  Listening for transport dt_socket at address: 60053[0m
[0m2021.07.21 17:39:37 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 17:39:40 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 17:39:40 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 17:39:40 INFO  Trying to attach to remote debuggee VM 127.0.0.1:60053 .[0m
[0m2021.07.21 17:39:40 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 17:39:43 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 17:39:43 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 17:39:43 INFO  [0m
[0m2021.07.21 17:39:43 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 17:39:43 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 17:39:43 INFO  also, here's a test: ?[0m
[0m2021.07.21 17:39:44 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 21, 2021 5:39:44 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: java.net.SocketException: Socket closed
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.net.SocketException: Socket closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at scala.meta.internal.metals.debug.SocketEndpoint.consume(SocketEndpoint.scala:22)
	at scala.meta.internal.metals.debug.MessageIdAdapter.consume(MessageIdAdapter.scala:43)
	at scala.meta.internal.metals.debug.ServerAdapter.send(ServerAdapter.scala:30)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$handleClientMessage$1(DebugProxy.scala:96)
	at scala.meta.internal.metals.debug.MessageIdAdapter.$anonfun$listen$1(MessageIdAdapter.scala:57)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at scala.meta.internal.metals.debug.SocketEndpoint.listen(SocketEndpoint.scala:26)
	at scala.meta.internal.metals.debug.MessageIdAdapter.listen(MessageIdAdapter.scala:47)
	at scala.meta.internal.metals.debug.DebugProxy.$anonfun$listenToClient$1(DebugProxy.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 21 more

[0m2021.07.21 17:40:31 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:40:31 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 2m 45.445s)[0m
[0m2021.07.21 17:40:31 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:40:41 INFO  time: compiled p0 in 9.07s[0m
[0m2021.07.21 17:40:45 INFO  Listening for transport dt_socket at address: 63409[0m
[0m2021.07.21 17:40:46 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 17:40:46 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 17:40:47 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 17:40:47 INFO  Trying to attach to remote debuggee VM 127.0.0.1:63409 .[0m
[0m2021.07.21 17:40:47 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 17:40:48 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 17:40:48 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 17:40:48 INFO  [0m
[0m2021.07.21 17:40:48 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 17:40:48 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 17:40:48 INFO  also, here's a test: ?[0m
[0m2021.07.21 17:40:48 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 17:41:54 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 4m 7.82s)[0m
[0m2021.07.21 17:41:54 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:41:54 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:42:00 INFO  time: compiled p0 in 6.32s[0m
[0m2021.07.21 17:42:06 INFO  Listening for transport dt_socket at address: 52288[0m
[0m2021.07.21 17:42:08 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 17:42:11 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 17:42:11 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 17:42:11 INFO  Trying to attach to remote debuggee VM 127.0.0.1:52288 .[0m
[0m2021.07.21 17:42:11 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 17:42:13 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 17:42:13 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 17:42:13 INFO  [0m
[0m2021.07.21 17:42:13 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 17:42:13 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 17:42:13 INFO  also, here's a test: ?[0m
[0m2021.07.21 17:42:13 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 17:58:02 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 20m 16.197s)[0m
[0m2021.07.21 17:58:02 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:58:02 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 17:58:10 INFO  time: compiled p0 in 7.38s[0m
[0m2021.07.21 17:58:16 INFO  Listening for transport dt_socket at address: 50140[0m
[0m2021.07.21 17:58:20 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 17:58:23 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 17:58:23 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 17:58:23 INFO  Trying to attach to remote debuggee VM 127.0.0.1:50140 .[0m
[0m2021.07.21 17:58:23 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 17:58:29 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 17:58:29 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 17:58:29 INFO  [0m
[0m2021.07.21 17:58:29 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 17:58:29 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 17:58:29 INFO  also, here's a test: ?[0m
[0m2021.07.21 17:58:29 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 21, 2021 6:24:55 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
Jul 21, 2021 6:25:13 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
Jul 21, 2021 6:25:43 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace
[0m2021.07.21 18:28:38 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:28:46 INFO  time: compiled p0 in 8.28s[0m
[0m2021.07.21 18:31:09 INFO  shutting down Metals[0m
[0m2021.07.21 18:31:09 INFO  Shut down connection with build server.[0m
[0m2021.07.21 18:31:09 INFO  Shut down connection with build server.[0m
No more data in the server stdin, exiting...
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
No more data in the server stdin, exiting...
No more data in the client stdin, exiting...
[0m2021.07.21 18:37:29 INFO  Started: Metals version 0.10.5 in workspace 'C:\Users\Shahrez\Documents\Revature\P0' for client Visual Studio Code 1.57.1.[0m
[0m2021.07.21 18:37:31 INFO  time: initialize in 1.42s[0m
[0m2021.07.21 18:37:33 INFO  Attempting to connect to the build server...[0m
[0m2021.07.21 18:37:32 WARN  no build target for: C:\Users\Shahrez\Documents\Revature\P0\src\main\scala\QUADRAT.scala[0m
[0m2021.07.21 18:37:33 INFO  skipping build import with status 'Installed'[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 32196'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:32196...
The server is listening for incoming connections at tcp://127.0.0.1:32196...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.21 18:37:37 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.21 18:37:37 INFO  Attempting to connect to the build server...[0m
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 27329'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:27329...
The server is listening for incoming connections at tcp://127.0.0.1:27329...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
[0m2021.07.21 18:37:39 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\bsp.trace.json[0m
[0m2021.07.21 18:37:39 INFO  time: Connected to build server in 6.22s[0m
[0m2021.07.21 18:37:39 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b[0m
[0m2021.07.21 18:37:41 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.21 18:37:42 INFO  time: Imported build in 0.53s[0m
[0m2021.07.21 18:37:44 INFO  no build target: using presentation compiler with only scala-library: 2.12.14[0m
[0m2021.07.21 18:37:53 INFO  time: code lens generation in 19s[0m
[0m2021.07.21 18:37:57 INFO  time: indexed workspace in 15s[0m
[0m2021.07.21 18:53:17 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 15m 40.294s)[0m
[0m2021.07.21 18:53:17 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:53:17 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:53:17 INFO  time: compiled p0 in 0.5s[0m
[0m2021.07.21 18:53:20 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:53:20 INFO  time: compiled p0 in 0.2s[0m
Jul 21, 2021 6:53:23 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 18:54:02 INFO  compiling p0 (1 scala source)[0m
Jul 21, 2021 6:54:03 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 18:54:05 INFO  time: compiled p0 in 2.73s[0m
[0m2021.07.21 18:54:27 INFO  Listening for transport dt_socket at address: 62268[0m
[0m2021.07.21 18:54:28 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 18:54:28 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 18:54:28 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 18:54:28 INFO  Trying to attach to remote debuggee VM 127.0.0.1:62268 .[0m
[0m2021.07.21 18:54:28 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 18:54:30 INFO  [0m
[0m2021.07.21 18:54:30 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 18:54:30 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 18:54:30 INFO  [0m
[0m2021.07.21 18:54:30 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 18:54:30 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 18:54:30 INFO  [0m
[0m2021.07.21 18:54:30 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 21, 2021 6:55:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 475
Jul 21, 2021 6:55:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 476
[0m2021.07.21 18:56:09 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:56:09 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 18m 31.932s)[0m
[0m2021.07.21 18:56:09 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:56:09 INFO  time: compiled p0 in 0.26s[0m
[0m2021.07.21 18:56:11 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:56:11 INFO  time: compiled p0 in 0.28s[0m
Jul 21, 2021 6:56:14 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

Jul 21, 2021 6:56:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 18:56:57 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 18:56:57 INFO  time: compiled p0 in 0.47s[0m
[0m2021.07.21 19:03:38 INFO  compiling p0 (1 scala source)[0m
Jul 21, 2021 7:03:39 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 19:03:43 INFO  time: compiled p0 in 4.45s[0m
[0m2021.07.21 19:03:51 INFO  Listening for transport dt_socket at address: 53474[0m
[0m2021.07.21 19:03:52 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 19:03:53 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 19:03:53 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 19:03:53 INFO  Trying to attach to remote debuggee VM 127.0.0.1:53474 .[0m
[0m2021.07.21 19:03:53 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 19:03:54 INFO  [0m
[0m2021.07.21 19:03:54 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 19:03:54 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 19:03:54 INFO  [0m
[0m2021.07.21 19:03:54 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 19:03:54 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 19:03:54 INFO  [0m
[0m2021.07.21 19:04:29 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 19:04:29 ERROR Exception in thread "main" [0m
[0m2021.07.21 19:04:29 INFO  Enter test value: [0m
[0m2021.07.21 19:05:00 INFO  Listening for transport dt_socket at address: 60673[0m
[0m2021.07.21 19:05:01 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 19:05:01 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 19:05:01 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 19:05:02 INFO  Trying to attach to remote debuggee VM 127.0.0.1:60673 .[0m
[0m2021.07.21 19:05:02 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 19:05:03 INFO  [0m
[0m2021.07.21 19:05:03 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 19:05:03 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 19:05:03 INFO  [0m
[0m2021.07.21 19:05:03 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 19:05:03 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 19:05:03 INFO  [0m
[0m2021.07.21 19:05:31 INFO  Enter test value: [0m
[0m2021.07.21 19:05:31 ERROR Exception in thread "main" [0m
[0m2021.07.21 19:05:31 INFO  Canceling debug proxy for [QUADRAT][0m
Jul 21, 2021 7:20:54 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:26:31 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.meta.internal.pc.completions.OverrideCompletions.scala$meta$internal$pc$completions$OverrideCompletions$$getMembers(OverrideCompletions.scala:162)
	at scala.meta.internal.pc.completions.OverrideCompletions$OverrideCompletion.contribute(OverrideCompletions.scala:61)
	at scala.meta.internal.pc.CompletionProvider.expected$1(CompletionProvider.scala:393)
	at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala:474)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:58)

Jul 21, 2021 7:26:43 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:26:44 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:26:45 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:26:45 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:29:30 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: null
Jul 21, 2021 7:29:32 PM scala.meta.internal.pc.CompletionProvider expected$1
WARNING: value <error: object input> is not a module
Jul 21, 2021 7:29:47 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object input
java.util.concurrent.CompletionException: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object input
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:42)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object input

Jul 21, 2021 7:30:55 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:30:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:59)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:30:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:59)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:36:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:28 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:50 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:55 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 32 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:59)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:37:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 33 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:59)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:38:23 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:38:33 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:38:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:59)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

Jul 21, 2021 7:38:41 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 28 is not a valid line number, allowed [0..27]
	at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
	at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
	at scala.meta.inputs.Input$VirtualFile.lineToOffset(Input.scala:80)
	at scala.meta.inputs.Position$Range$.lineLength$1(Position.scala:57)
	at scala.meta.inputs.Position$Range$.apply(Position.scala:60)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionPositionLspInverse.toMeta(MtagsEnrichments.scala:121)
	at scala.meta.internal.parsing.Trees.$anonfun$findLastEnclosingAt$5(Trees.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.parsing.Trees.findLastEnclosingAt(Trees.scala:70)
	at scala.meta.internal.metals.codeactions.InsertInferredType.$anonfun$contribute$1(InsertInferredType.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	... 4 more

[0m2021.07.21 19:39:15 INFO  Deduplicating compilation of p0 from bsp client 'Metals 0.10.5' (since 1h 1m 37.997s)[0m
[0m2021.07.21 19:39:15 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 19:39:15 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 19:39:15 INFO  time: compiled p0 in 0.47s[0m
[0m2021.07.21 19:39:18 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 19:39:18 INFO  time: compiled p0 in 0.21s[0m
Jul 21, 2021 7:39:20 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Compilation not successful
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

Jul 21, 2021 7:39:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 19:39:50 INFO  compiling p0 (1 scala source)[0m
Jul 21, 2021 7:39:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 19:39:52 INFO  time: compiled p0 in 1.12s[0m
Jul 21, 2021 7:40:01 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 19:41:01 INFO  compiling p0 (1 scala source)[0m
Jul 21, 2021 7:41:01 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 19:41:01 INFO  time: compiled p0 in 0.82s[0m
[0m2021.07.21 19:46:08 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 19:46:08 INFO  time: compiled p0 in 0.83s[0m
[0m2021.07.21 19:47:12 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 19:47:16 INFO  time: compiled p0 in 3.63s[0m
[0m2021.07.21 19:48:23 INFO  Listening for transport dt_socket at address: 56727[0m
[0m2021.07.21 19:48:24 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 19:48:25 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 19:48:25 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 19:48:25 INFO  Trying to attach to remote debuggee VM 127.0.0.1:56727 .[0m
[0m2021.07.21 19:48:25 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 19:48:26 INFO  [0m
[0m2021.07.21 19:48:26 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 19:48:26 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 19:48:26 INFO  [0m
[0m2021.07.21 19:48:26 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 19:48:26 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 19:48:26 INFO  [0m
[0m2021.07.21 19:49:03 INFO  Enter test value: [0m
[0m2021.07.21 19:49:03 ERROR Exception in thread "main" [0m
[0m2021.07.21 19:49:03 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 20:06:03 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:06:03 INFO  time: compiled p0 in 0.64s[0m
[0m2021.07.21 20:07:42 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:07:42 INFO  time: compiled p0 in 0.53s[0m
Jul 21, 2021 8:07:46 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

Jul 21, 2021 8:07:50 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.meta.internal.metals.debug.WorkspaceErrorsException$: Cannot run class, since the workspace has errors.
	at scala.meta.internal.metals.debug.WorkspaceErrorsException$.<clinit>(DebugProvider.scala)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$2(DebugProvider.scala:332)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

[0m2021.07.21 20:08:51 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:08:51 INFO  time: compiled p0 in 0.37s[0m
[0m2021.07.21 20:09:39 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:09:39 INFO  time: compiled p0 in 0.59s[0m
[0m2021.07.21 20:11:22 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:11:25 INFO  time: compiled p0 in 3.09s[0m
[0m2021.07.21 20:11:31 INFO  Listening for transport dt_socket at address: 61558[0m
[0m2021.07.21 20:11:32 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 20:11:32 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 20:11:33 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 20:11:33 INFO  Trying to attach to remote debuggee VM 127.0.0.1:61558 .[0m
[0m2021.07.21 20:11:33 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 20:11:33 INFO  [0m
[0m2021.07.21 20:11:33 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 20:11:33 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 20:11:33 INFO  [0m
[0m2021.07.21 20:11:33 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 20:11:33 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 20:11:33 INFO  [0m
[0m2021.07.21 20:11:41 INFO  Enter test value: [0m
[0m2021.07.21 20:11:41 ERROR Exception in thread "main" [0m
[0m2021.07.21 20:11:41 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 20:14:12 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:14:15 INFO  time: compiled p0 in 2.6s[0m
[0m2021.07.21 20:17:38 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:17:40 INFO  time: compiled p0 in 2.05s[0m
[0m2021.07.21 20:20:04 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:20:09 INFO  time: compiled p0 in 4.91s[0m
[0m2021.07.21 20:22:11 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:22:14 INFO  time: compiled p0 in 2.75s[0m
[0m2021.07.21 20:22:20 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:22:23 INFO  time: compiled p0 in 2.78s[0m
[0m2021.07.21 20:25:59 INFO  Listening for transport dt_socket at address: 64881[0m
[0m2021.07.21 20:26:01 INFO  tracing is disabled for protocol dap-server, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-server.trace.json[0m
[0m2021.07.21 20:26:01 INFO  tracing is disabled for protocol dap-client, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\Shahrez\AppData\Local\scalameta\metals\cache\dap-client.trace.json[0m
[0m2021.07.21 20:26:01 INFO  Starting debug proxy for [QUADRAT][0m
[0m2021.07.21 20:26:01 INFO  Trying to attach to remote debuggee VM 127.0.0.1:64881 .[0m
[0m2021.07.21 20:26:01 INFO  Attaching to debuggee VM succeeded.[0m
[0m2021.07.21 20:26:03 INFO  [0m
[0m2021.07.21 20:26:03 INFO  Welcome to QUADRAT, a program that allows you[0m
[0m2021.07.21 20:26:03 INFO  to effortlessly solve quadratic equations![0m
[0m2021.07.21 20:26:03 INFO  [0m
[0m2021.07.21 20:26:03 INFO  All you have to do is enter the values for a, b and c[0m
[0m2021.07.21 20:26:03 INFO  from the equation in the form of ax^2 + bx + c = 0[0m
[0m2021.07.21 20:26:03 INFO  [0m
[0m2021.07.21 20:26:11 ERROR [error response][evaluate]: an implementation is missing[0m
[0m2021.07.21 20:26:18 ERROR [error response][evaluate]: an implementation is missing[0m
[0m2021.07.21 20:26:18 INFO  Enter test value: [0m
[0m2021.07.21 20:26:18 INFO  Canceling debug proxy for [QUADRAT][0m
[0m2021.07.21 20:28:08 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:28:08 INFO  time: compiled p0 in 0.59s[0m
[0m2021.07.21 20:34:26 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:34:30 INFO  time: compiled p0 in 3.97s[0m
[0m2021.07.21 20:39:13 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:39:13 INFO  time: compiled p0 in 0.62s[0m
[0m2021.07.21 20:42:45 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:42:48 INFO  time: compiled p0 in 3.55s[0m
[0m2021.07.21 20:43:10 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:43:13 INFO  time: compiled p0 in 3.1s[0m
Jul 21, 2021 8:46:13 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
Jul 21, 2021 8:46:13 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.reflect.internal.Definitions$DefinitionsClass.isByNameParamType(Definitions.scala:417)
	at scala.reflect.internal.TreeInfo.isStableIdent(TreeInfo.scala:140)
	at scala.reflect.internal.TreeInfo.isStableIdentifier(TreeInfo.scala:113)
	at scala.reflect.internal.TreeInfo.isPath(TreeInfo.scala:102)
	at scala.reflect.internal.TreeInfo.admitsTypeSelection(TreeInfo.scala:158)
	at scala.tools.nsc.interactive.Global.stabilizedType(Global.scala:960)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:808)
	at scala.meta.internal.pc.SignatureHelpProvider.signatureHelp(SignatureHelpProvider.scala:23)

[0m2021.07.21 20:48:08 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:48:12 INFO  time: compiled p0 in 3.82s[0m
[0m2021.07.21 20:50:51 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:50:54 INFO  time: compiled p0 in 2.25s[0m
[0m2021.07.21 20:58:00 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 20:58:04 INFO  time: compiled p0 in 3.52s[0m
[0m2021.07.21 21:20:42 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 21:20:45 INFO  time: compiled p0 in 2.76s[0m
Jul 21, 2021 9:32:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 4718
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[String]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 82, 82, 95)
[0m2021.07.21 21:34:23 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 21:34:27 INFO  time: compiled p0 in 4.33s[0m
[0m2021.07.21 21:36:58 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 21:37:02 INFO  time: compiled p0 in 3.18s[0m
[0m2021.07.21 21:41:16 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 21:41:20 INFO  time: compiled p0 in 3.4s[0m
[0m2021.07.21 21:43:40 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 21:43:43 INFO  time: compiled p0 in 2.5s[0m
[0m2021.07.21 22:06:14 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:06:17 INFO  time: compiled p0 in 2.86s[0m
[0m2021.07.21 22:28:59 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:29:03 INFO  time: compiled p0 in 4.35s[0m
Jul 21, 2021 10:42:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8837
Jul 21, 2021 10:42:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8838
Jul 21, 2021 10:42:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8840
[0m2021.07.21 22:43:49 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:43:53 INFO  time: compiled p0 in 4.11s[0m
[0m2021.07.21 22:45:41 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:45:43 INFO  time: compiled p0 in 2.58s[0m
[0m2021.07.21 22:47:23 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:47:27 INFO  time: compiled p0 in 3.95s[0m
[0m2021.07.21 22:51:11 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:51:14 INFO  time: compiled p0 in 2.58s[0m
[0m2021.07.21 22:55:10 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:55:13 INFO  time: compiled p0 in 3.31s[0m
[0m2021.07.21 22:57:26 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 22:57:29 INFO  time: compiled p0 in 3.06s[0m
[0m2021.07.21 23:00:48 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:00:51 INFO  time: compiled p0 in 3s[0m
[0m2021.07.21 23:03:21 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:03:24 INFO  time: compiled p0 in 2.36s[0m
Jul 21, 2021 11:05:14 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
Jul 21, 2021 11:05:14 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.reflect.internal.Definitions$DefinitionsClass.isByNameParamType(Definitions.scala:417)
	at scala.reflect.internal.TreeInfo.isStableIdent(TreeInfo.scala:140)
	at scala.reflect.internal.TreeInfo.isStableIdentifier(TreeInfo.scala:113)
	at scala.reflect.internal.TreeInfo.isPath(TreeInfo.scala:102)
	at scala.reflect.internal.TreeInfo.admitsTypeSelection(TreeInfo.scala:158)
	at scala.tools.nsc.interactive.Global.stabilizedType(Global.scala:960)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:808)
	at scala.meta.internal.pc.SignatureHelpProvider.signatureHelp(SignatureHelpProvider.scala:23)

Jul 21, 2021 11:18:50 PM scala.meta.internal.pc.CompilerAccess retryWithCleanCompiler
INFO: compiler crashed due to an error in the Scala compiler, retrying with new compiler instance.
Jul 21, 2021 11:18:50 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.lang.NullPointerException
	at scala.reflect.internal.Definitions$DefinitionsClass.isByNameParamType(Definitions.scala:417)
	at scala.reflect.internal.TreeInfo.isStableIdent(TreeInfo.scala:140)
	at scala.reflect.internal.TreeInfo.isStableIdentifier(TreeInfo.scala:113)
	at scala.reflect.internal.TreeInfo.isPath(TreeInfo.scala:102)
	at scala.reflect.internal.TreeInfo.admitsTypeSelection(TreeInfo.scala:158)
	at scala.tools.nsc.interactive.Global.stabilizedType(Global.scala:960)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:808)
	at scala.meta.internal.pc.SignatureHelpProvider.signatureHelp(SignatureHelpProvider.scala:23)

[0m2021.07.21 23:29:44 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:29:44 INFO  time: compiled p0 in 0.97s[0m
[0m2021.07.21 23:30:16 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:30:16 INFO  time: compiled p0 in 0.5s[0m
Jul 21, 2021 11:31:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 11120
[0m2021.07.21 23:32:20 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:32:20 INFO  time: compiled p0 in 0.32s[0m
[0m2021.07.21 23:36:07 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:36:07 INFO  time: compiled p0 in 0.5s[0m
[0m2021.07.21 23:36:21 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:36:35 INFO  time: compiled p0 in 14s[0m
[0m2021.07.21 23:37:43 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:37:43 INFO  time: compiled p0 in 0.74s[0m
[0m2021.07.21 23:42:18 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:42:21 INFO  time: compiled p0 in 2.9s[0m
[0m2021.07.21 23:52:31 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:52:34 INFO  time: compiled p0 in 2.88s[0m
something's wrong: no file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala in Array[String]RangePosition(file:///C:/Users/Shahrez/Documents/Revature/P0/src/main/scala/QUADRAT.scala, 169, 169, 182)
[0m2021.07.21 23:58:55 INFO  compiling p0 (1 scala source)[0m
[0m2021.07.21 23:58:58 INFO  time: compiled p0 in 2.97s[0m
